Controllers/PacotesTuristicosController.cs
using System.Collections.Generic;
using Viagem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace Viagem.Controllers
{
    public class PacotesTuristicosController : Controller
    {
        public IActionResult Cadastro()
        {
             if(HttpContext.Session.GetInt32("idUsuario")== null)
                return RedirectToAction("Login","Usuario");
            return View();
        }
        [HttpPost]
        public IActionResult Cadastro(PacotesTuristicos novo)
        {   
            if(HttpContext.Session.GetInt32("idUsuario") == null)
                return RedirectToAction("Login", "Usuario");
            PacotesTuristicosBanco pacoteBanco = new PacotesTuristicosBanco();
            int id = (int)HttpContext.Session.GetInt32("idUsuario");
            pacoteBanco.Inserir(novo,id );
            ViewBag.Mensagem = "Cadastro concluido com sucesso";
            return View();
        }
        public IActionResult Lista()
        {
          
            PacotesTuristicosBanco pacote = new PacotesTuristicosBanco();
            List<PacotesTuristicos> lista = pacote.BuscarTodos();
            return View(lista);
        }
       
        [HttpPost]
        public IActionResult Login(Usuario usuario)
        {
            UsuarioBanco usuarioBanco = new UsuarioBanco();
            Usuario usuarioSessao = usuarioBanco.BuscaUsuario(usuario);

            if(usuarioSessao != null)
            {
                ViewBag.Mensagem = "Voce esta logado!";
                HttpContext.Session.SetInt32("idUsuario", usuarioSessao.Id);
                HttpContext.Session.SetString("nomeUsuario", usuarioSessao.Nome);
                return View();
            }else
            {
                ViewBag.Mensagem = " Falha no login";
                return View();
            }
        }
        
        
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Viagem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Viagem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""   asp-controller="PacotesTuristicos" asp-action="lista">Ver Pacotes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pacotesturisticos" asp-action="Cadastro"> Cadastrar Pacotes</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Lista"> Ver Usuarios</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Cadastro"> Cadastrar Usuarios</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="QuemSomos"> Quem Somos</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login"> Login</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="FaleConosco"> FaleConosco</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Lista"> Mensagens</a>
                        </li>
                          @if(Context.Session.GetInt32("idUsuario") != null)
                        {
                        <li class="nav-item">Olá @Context.Session.GetString("nomeUsuario")<a asp-controller="Usuario" class="nav-link text-dark" asp-action="Logout">sair </a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Viagem - <a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>